### PR TITLE
Fix TS type definition

### PR DESCRIPTION
**Pull request by gstamac**
Typescript type definitions are wrong and unusable. I fixed them and added `defaults` variable.

### CODE REVIEW

**Comment by mauricedb** [comment]
@gstamac Thanks for the PR. Merged and just published an update.

**Comment by gstamac** [comment]
@mauricedb great thanks. That was quick. I have some other ideas if you are willing to accept PRs.

**Comment by mauricedb** [comment]
@gstamac 🔥 Sure always happy to accept PR's. But if it's more than trivial I would recommend opening an issue first so we can discuss if it is something I would like to accept. Just to avoid doing a lot of work with the possibility of me wanting to go another direction,

**Comment by gstamac** [comment]
Done.

**Pull request merged**
